# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    exclude: 
    - u/*

stages:
- stage: RunBenchmark
  jobs:
  - job: run
    strategy:
      matrix:
        'Win64':
          image: 'windows-latest'
          mlnet: 'microsoft.ml.modelbuilder.cli.win64'
          artifact: 'win64'
        'Ubuntu latest':
          image: 'ubuntu-latest'
          mlnet: 'microsoft.ml.modelbuilder.cli.linux64'
          artifact: 'linux'
        'MacOS Big Sur':
          image: 'macOS-11'
          mlnet: 'microsoft.ml.modelbuilder.cli.osx'
          artifact: 'macOS'
    pool:
      vmImage: $(image)
      demands: cmd
    cancelTimeoutInMinutes: 60
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'create manifest'
      inputs:
        command: 'custom'
        custom: 'new'
        arguments: 'tool-manifest'
        
    - task: DotNetCoreCLI@2
      displayName: 'install mlnet cli'
      inputs:
        command: 'custom'
        custom: 'msbuild'
        arguments: 'InstallMLNet.proj'

    - task: DotNetCoreCLI@2
      displayName: 'run benchmark'
      inputs:
        command: 'custom'
        custom: 'msbuild'
        arguments: 'Run.proj'

    - task: CopyFiles@2
      displayName: Copy log and mbconfig to artifact
      inputs:
        Contents: |
          Output/**/*.mbconfig
          Output/**/*.txt
        TargetFolder: '$(Build.ArtifactStagingDirectory)Artifacts/$(artifact)'

    - task: PublishBuildArtifacts@1
      displayName: Upload artifact
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)Artifacts'
        ArtifactName: 'Artifacts'
        publishLocation: 'Container'
- stage: Validation
  pool: 
    vmImage: 'windows-latest'
  dependsOn: 'RunBenchmark'
  jobs:
  - job: Validate
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'Artifacts'
        itemPattern: '**/*.mbconfig'
        path: 'Output'
    - task: DotNetCoreCLI@2
      displayName: Generate benchmark result
      inputs:
        command: 'custom'
        custom: 'msbuild'
        arguments: 'Train.proj -t:GenerateReportFile'
    - task: PublishBuildArtifacts@1
      displayName: Upload result
      inputs:
        PathtoPublish: 'result.csv'
        ArtifactName: 'result'
        publishLocation: 'Container'
