# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    exclude: 
    - u/*

stages:
- stage: RunBenchmark
  jobs:
  - job: run
    strategy:
      maxParallel: 5
      matrix:
        'Win64':
          image: 'windows-latest'
        'Ubuntu x64':
          image: 'ubuntu-latest'
        'MacOS arm64':
          image: 'macOS-13-arm64'
    pool:
      vmImage: $(image)
      demands: cmd
    cancelTimeoutInMinutes: 60
    steps:
    - task: UseDotNet@2
      displayName: Use .NET 6.0
      inputs:
        useGlobalJson: true
    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet'
    - task: NuGetAuthenticate@1
      inputs:
        forceReinstallCredentialProvider: true
    - script: |
        cd MLNetBenchmark && cd MLNetBenchmark && dotnet run
      displayName: 'Run Benchmark'
